### ISSUE TITLE
Research external authorization options

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/csv2wiki#16]
We'd like to be able to use some shared authn/authz system for our instance of Mediawiki.  What are the options available?  Does Mediawiki support LDAP?

**Comment by cecilia-donnelly** [comment]
This [LDAP Extension](https://www.mediawiki.org/wiki/Extension:LDAP_Authentication) promises to support LDAP for Mediawiki, but does not work for Mediawiki versions >= 1.27 and doesn't appear to have been updated since 2014.  There was discussion [here](https://www.mediawiki.org/wiki/Topic:U6tc39jwk2pjhb62) about 9 months ago about updating the extension (since Mediawiki has now moved forward and the old extension isn't fully compatible).  One of the commenters pointed to the [remoteuser extension](https://www.mediawiki.org/wiki/Extension:Auth_remoteuser), which is under active development (latest release was just a few months ago) and seems like it might satisfy our requirements.

Because the remoteuser extension uses the `REMOTE_USER` environment variable, it appears possible to use several different auth modules.  See the [Apache](https://www.mediawiki.org/wiki/Extension:Auth_remoteuser#Apache) section of the documentation.

**Comment by cecilia-donnelly** [comment]
Evidently this is an area of interest for others - after the 2017 hackathon, a [draft page about LDAP hub](https://www.mediawiki.org/wiki/LDAP_hub) was created, but is still a spec.  If we wanted, we could probably contribute some of this functionality back to Mediawiki itself.

We might also look at the [user identity extensions](https://www.mediawiki.org/wiki/Category:User_identity_extensions) category, which includes several different external auth providers.  OAuth, OpenID, ULogin, Shibboleth, and SAML are all represented.

Based on general web searching, the remoteuser extension I linked to above is probably the way to go.  It seems flexible, under active development, and widely used.  However, if we want to work with a system that already depends on [Shibboleth](https://www.mediawiki.org/wiki/Extension:Shibboleth), say, then that extension might be a good option.

**Comment by kfogel** [comment]
Hey, @cecilia-donnelly and @frankduncan.  Can we move this ticket (well, copy its data I guess) over to the `librehq-wikis` repository?

**Comment by kfogel** [comment]
(+1 on the findings, thank you; I've followed the links and read a bit and agree that remoteuser looks like the way to go here)

**Comment by frankduncan** [comment]
Moved to OpenTechStrategies/librehq-wikis/issues/2
